#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBE793007AD22DF7E (tsujan2000@gmail.com)
#
Name     : lxqt-sudo
Version  : 1.0.0
Release  : 9
URL      : https://github.com/lxqt/lxqt-sudo/releases/download/1.0.0/lxqt-sudo-1.0.0.tar.xz
Source0  : https://github.com/lxqt/lxqt-sudo/releases/download/1.0.0/lxqt-sudo-1.0.0.tar.xz
Source1  : https://github.com/lxqt/lxqt-sudo/releases/download/1.0.0/lxqt-sudo-1.0.0.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : liblxqt-dev
BuildRequires : qtbase-dev

%description
# lxqt-sudo
## Overview
lxqt-sudo is a graphical front-end of commands `sudo` and `su` respectively. As such it enables regular users to launch applications with permissions of other users including root.

%prep
%setup -q -n lxqt-sudo-1.0.0
cd %{_builddir}/lxqt-sudo-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636129557
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1636129557
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-sudo
cp %{_builddir}/lxqt-sudo-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/lxqt-sudo/7fab4cd4eb7f499d60fe183607f046484acd6e2d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
